swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:5000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - text/plain
# format of the responses to the client (Accepts)
produces:
  - text/javascript
  - application/json
x-a127-config: {}
x-a127-services: {}
paths:
  /streams:
    # binds a127 app logic to a route
    x-swagger-router-controller: streams
    x-a127-apply: {}
    get:
      description: Returns bitrates by session
      # used as the method name of the controller
      operationId: getStreamItems
      parameters:
        - name: session_id
          in: query
          description: session_id to get list of bitrates for
          required: true
          type: string
        - name: user_id
          in: query
          description: user_id to get list of bitrates for
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ErrorResponse"
            # a pointer to a definition
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /streams/upload:
    x-swagger-router-controller: streams
    x-a127-apply: {}
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: putUploadItem
      parameters:
        - name: name
          in: body
          description: Desc
          required: false
          schema:
            type: string
      responses:
        "201":
          description: Created
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /streams/download:
    x-swagger-router-controller: streams
    x-a127-apply: {}
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: putDownloadItem
      parameters:
        - name: name
          in: body
          description: Desc
          required: false
          schema:
            type: string
      responses:
        "201":
          description: Created
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
          
  /network:
    # binds a127 app logic to a route
    x-swagger-router-controller: network
    x-a127-apply: {}
    get:
      description: Returns bitrates by session
      # used as the method name of the controller
      operationId: getNetworkItems
      parameters:
        - name: session_id
          in: query
          description: session_id to get list of bitrates for
          required: true
          type: string
        - name: user_id
          in: query
          description: user_id to get list of bitrates for
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ErrorResponse"
            # a pointer to a definition
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /network/upload:
    x-swagger-router-controller: network
    x-a127-apply: {}
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: putUploadNetworkItem
      parameters:
        - name: name
          in: body
          description: Desc
          required: false
          schema:
            type: string
      responses:
        "201":
          description: Created
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /network/download:
    x-swagger-router-controller: network
    x-a127-apply: {}
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: putDownloadNetworkItem
      parameters:
        - name: name
          in: body
          description: Desc
          required: false
          schema:
            type: string
      responses:
        "201":
          description: Created
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"          
            
  /events:
    # binds a127 app logic to a route
    x-swagger-router-controller: events
    x-a127-apply: {}
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: getEventList
      parameters:
        - name: session_id
          in: query
          description: Desc
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: createEvent
      parameters:
        - name: name
          in: body
          description: Desc
          required: false
          schema:
            type: string
      responses:
        "201":
          description: Created
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    type: string
  ErrorResponse:
    type: string