swagger: "2.0"
info:
  version: "0.0.1"
  title: Live Diagnostic Api
# during dev, should point to your local machine
host: localhost:5000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config: {}
x-a127-services: {}
paths:
  /session_infos:
    # binds a127 app logic to a route
    x-swagger-router-controller: session_infos
    x-a127-apply: {}
    get:
      description: Returns session info by session
      # used as the method name of the controller
      operationId: getSessionInfoItems
      parameters:
        - name: session_id
          in: query
          description: session_id to get list of bitrates for
          required: true
          type: string
        - name: user_id
          in: query
          description: user_id to get list of bitrates for
          required: false
          type: string
      responses:
        200:
          description: Success
        401:
          description: Unauthorized
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: putSessionInfoItem
      parameters:
        - name: name
          in: body
          description: Desc
          required: false
          schema:
            type: string
      responses:
        "201":
          description: Created
        # responses may fall through to errors
        default:
          description: Error
  /events:
    # binds a127 app logic to a route
    x-swagger-router-controller: events
    x-a127-apply: {}
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: getEventList
      parameters:
        - name: session_id
          in: query
          description: Desc
          required: false
          type: string
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: createEvent
      parameters:
        - name: name
          in: body
          description: Desc
          required: false
          schema:
            type: string
      responses:
        "201":
          description: Created
        # responses may fall through to errors
        default:
          description: Error
